<?xml version="1.0"?>
<package>
  <name>tcrlm</name>
  <version>1.0.0</version>
  <description>Terrain Confidence Region-Guided LiDAR Mapping (TCR-LM).</description>

  <maintainer email="ikaros.yuki.93@gmail.com">Ziyu Zhao</maintainer>

  <license>BSD-3-Clause</license>

  <author email="ikaros.yuki.93@gmail.com">Ziyu Zhao</author>

  <buildtool_depend>catkin</buildtool_depend>

  <build_depend>roscpp</build_depend>
  <run_depend>roscpp</run_depend>
  <build_depend>tf</build_depend>
  <run_depend>tf</run_depend>

  <build_depend>pcl_conversions</build_depend>
  <run_depend>pcl_conversions</run_depend>

  <build_depend>std_msgs</build_depend>
  <run_depend>std_msgs</run_depend>
  <build_depend>sensor_msgs</build_depend>
  <run_depend>sensor_msgs</run_depend>
  <build_depend>geometry_msgs</build_depend>
  <run_depend>geometry_msgs</run_depend>
  <build_depend>nav_msgs</build_depend>
  <run_depend>nav_msgs</run_depend>
  <build_depend>visualization_msgs</build_depend>
  <run_depend>visualization_msgs</run_depend>
  <run_depend>rviz</run_depend>
  <run_depend>rosbag</run_depend>

  <build_depend>message_generation</build_depend>
  <build_depend>message_runtime</build_depend>
  <run_depend>message_runtime</run_depend>

  <build_depend>GTSAM</build_depend>
  <run_depend>GTSAM</run_depend>
  <build_depend>boost</build_depend>
  <run_depend>boost</run_depend>

</package>
